### ISSUE TITLE
QgsMessageBar.INFO/WARNING error

### ISSUE THREAD

**Issue by luipir** [camptocamp/QGIS-SpreadSheetLayers#21]
qgsi API changed. Use Qgis.Info/Warning instead

**Comment by luipir** [comment]
for some reason the code fro master works, but I had problem with installed version from repo. Probly some fault installing. Closing the issue

**Comment by arnaud-morvan** [comment]
It seems this have been fixed but not yet released, will do it now. Thanks @luipir for raising this.

**Comment by luipir** [comment]
to you @arnaud-morvan
