### ISSUE TITLE
Can't reopen a file

### ISSUE THREAD

**Issue by aldeano** [camptocamp/QGIS-SpreadSheetLayers#3]
When i close a spreadsheet, edit something in excel and reopen the file in qgis, i can't open it again, and this message appears (under a yellowish colour):
Could not open C:/Users/my.user/Documents/GIS DataBase/file.xlsx
I'm using qgis 2.10.1 in win7 x64. Deleting the vrt file doesn't change this situation.

**Comment by arnaud-morvan** [comment]
Have you tried to close QGIS.
If you open file.xlsx directly in QGIS, remove it, edit the file, and open it again with closing QGIS, you should have the same issue.
This issue do not seems to be related to the plugin, probably QGIS itself or GDAL/OGR.

**Comment by aldeano** [comment]
Yes, if i close qgis, edit the file, and reopen qgis it's possible, but it's not the way i expected to work, because i have other shapes opened, so close an reopen qgis and the layers only to edit a xlsx file it's not ideal. There's a way to obtain a log of this error message in win7?

**Comment by arnaud-morvan** [comment]
I get this message in the log message panel (menu View/Panels/Log message panel), in OGR tab: "Source de données invalide (GotoFileOffset failed)"
I suppose that GDAL/OGR keep the file open, even when removed from layer tree.
This is not related to the plugin, so I close this ticket.
Maybe you can file a ticket on QGIS tracker: https://hub.qgis.org/projects/quantum-gis
or ask the developper list: qgis-developer@lists.osgeo.org
