### ISSUE TITLE
Is it possible to add Japanese language?

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [camptocamp/QGIS-SpreadSheetLayers#30]
Is it possible to add Japanese language?
I will create the Japanese TS file for you.

**Comment by arnaud-morvan** [comment]
Hello @yamamoto-ryuzo 

I just fixed the string collector : https://github.com/camptocamp/QGIS-SpreadSheetLayers/pull/31

So yes, provide the TS file and we will add Japanese language.

Regards

Arnaud

**Comment by yamamoto-ryuzo** [comment]
https://github.com/camptocamp/QGIS-SpreadSheetLayers/pull/32
Was I correct in my PULL request?
Should I have attached only the file?
