### ISSUE TITLE
Croatian characters (UTF-8) unsupported in header of spreadsheet

### ISSUE THREAD

**Issue by igadmile** [camptocamp/QGIS-SpreadSheetLayers#4]
While selecting "Header at first line" on spreadsheet which has Croatian characters (ČĆŠĐŽ) returns error:

UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 3: ordinal not in range(128)

Test file link here (github has problem with processing of file):
https://mega.nz/#!T1NG3LjA!ElJ0ZfaJPrLSGxtxOXjGt4sA5UWuSj1R7Fz9HVU96LE

**Comment by antoniusz** [comment]
The same error with Hungarian characters.
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
sample file:
http://jupiter.elte.hu/111veglegesvar/gpsexcel.xls

**Comment by yjacolin** [comment]
Thanks for your feedback, we will work on this on the next hackfest (in may).

**Comment by arnaud-morvan** [comment]
Should have been fixed, it seems works now. Feel free to re-open.
