### ISSUE TITLE
Error launching SpreadsheetLayers

### ISSUE THREAD

**Issue by GBT-Unice** [camptocamp/QGIS-SpreadSheetLayers#50]
The error occurs when launching the widget.

AttributeError: type object 'QgsWkbTypes' has no attribute 'translatedDisplayString' 
Traceback (most recent call last):
  File "/Users/gbt/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpreadsheetLayers/widgets/SpreadsheetLayersDialog.py", line 100, in data
    return QgsWkbTypes.translatedDisplayString(geometry_type[0])
AttributeError: type object 'QgsWkbTypes' has no attribute 'translatedDisplayString'

Version de Python : 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Version de QGIS : 3.8.3-Zanzibar Zanzibar, exported 

Chemin Python :
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python
/Users/gbt/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gbt/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/gbt/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gbt/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/Users/gbt/Desktop/ALIR Prochain Volume/ALiR CARTO/Carto

**Comment by arnaud-morvan** [comment]
I create a new release: https://plugins.qgis.org/plugins/SpreadsheetLayers/version/2.1.2/
Hope it will be approved soon.
Regards

**Comment by GBT-Unice** [comment]
I installed the new version, the error message disappeared. Thanks




Le 29 févr. 2024 à 08:30, Arnaud Morvan ***@***.***> a écrit :

Ce message provient d’un expéditeur externe à l’université (adresse : ***@***.***). Ne cliquez pas sur les liens et n’ouvrez pas les pièces jointes si vous ne connaissez pas l’expéditeur ou que vous n’êtes pas sûr du contenu. En cas de doute, merci de transférer le mail à ***@***.***

I create a new release: https://plugins.qgis.org/plugins/SpreadsheetLayers/version/2.1.2/ <https://plugins.qgis.org/plugins/SpreadsheetLayers/version/2.1.2/>
Hope it will be approved soon.
Regards
