### ISSUE TITLE
Using Spreadsheet layers in the graphical modeler ?

### ISSUE THREAD

**Issue by kazemar** [camptocamp/QGIS-SpreadSheetLayers#55]
Hi,

Is there a way to use Spreadsheet layers in the graphical modeler ? I would like to make a processing model that can download xls files and copy a part of the data in my database.

Thanks !

**Comment by arnaud-morvan** [comment]
In fact the SpreadsheetLayers plugins is just a dialog to create an OGR VRT file.

If your xls file always have the same structure, you can use the plugin to create a VRT file and create a modeler to import your data using standard OGR provider.
